baseURL:         "http://2017.deolhonasmetas.org.br/"
languageCode:    "pt-br"
title:           "De Olho nas Metas - 2017"
disableKinds:    ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
googleAnalytics: ""
metaDataFormat:  "yaml"
params:
  Subtitle:      "gestão 2017"
  AuthorName:    "AppCívico"
  GitHubUser:    "AppCivico"
  googleMapsAPI: "AIzaSyBHIYUva7giKEo0zcgX8x8HFTCWSCW4IgU"
  responsibles:
    redeNossaSaoPaulo:
      name: Rede Nossa São Paulo
      link: http://www.nossasaopaulo.org.br
  partners:
    mitMl:
      name: mit media lab
      link: http://civic.mit.edu
    tbcSP:
      name: Tribunal de Contas do Município de São Paulo
      link: http://www.tcm.sp.gov.br
  supporters:
    avina:
      name: Fundación Avina
      link: http://www.avinaamericas.org
