baseURL:         "http://2017.deolhonasmetas.org.br/"
languageCode:    "pt-br"
title:           "De Olho nas Metas - 2017"
disableKinds:    ["taxonomy", "taxonomyTerm", "RSS"]
enableRobotsTXT: true
googleAnalytics: "UA-10515816-3"
metaDataFormat:  "yaml"
enableMissingTranslationPlaceholders: true
defaultContentLanguage: pt
disableFastRender: true
ignoreFiles: [ "\\.tmp$", "\\.tmp-browserify" ]
stepAnalysis: true
templateMetrics: true
pluralizeListTitles: false
menu:
  main:
      - Name: "O que é?"
        Pre: ""
        Weight: 1
        Identifier: "o-que-e"
        URL: "/o-que-e/"
      - Name: "Distritos"
        Pre: ""
        Weight: 2
        Identifier: "distritos"
        URL: "/distritos/"
      - Name: "Metas"
        Pre: ""
        Weight: 3
        Identifier: "metas"
        URL: "/metas/"
      - Name: "Indicadores"
        Pre: ""
        Weight: 4
        Identifier: "indicadores"
        URL: "/indicadores/"
      - Name: "Empresas"
        Pre: ""
        Weight: 5
        Identifier: "empresas"
        URL: "/empresas/"
      - Name: "Dados abertos"
        Pre: ""
        Weight: 6
        Identifier: "dados-abertos"
        URL: "/dados-abertos/"
params:
  Subtitle:      "gestão 2017"
  AuthorName:    "AppCívico"
  GitHubUser:    "AppCivico"
  googleMapsAPI: "AIzaSyDqT0PwlW6s3z_DmUF47L6A9bSTwNAyoYs"
  domainAPI:
    dev: "https://dapidonm.eokoe.com"
    homol: "https://hapidonm.eokoe.com"
    prod: "https://2017.deolhonasmetas.org.br/api"

  responsibles:
    redeNossaSaoPaulo:
      name: Rede Nossa São Paulo
      link: http://www.nossasaopaulo.org.br
      logo: logo-rnsp-footer.png

  partners:
    mitMl:
      name: mit media lab
      link: http://civic.mit.edu
      logo: logo-mit-footer.png

    tbcSP:
      name: Tribunal de Contas do Município de São Paulo
      link: http://www.tcm.sp.gov.br
      logo: logo-tcm-footer.png

  supporters:
    avina:
      name: Fundación Avina
      link: http://www.avinaamericas.org
      logo: logo-avina-footer.png
